name = "LQGames"
uuid = "9f5465f2-6c52-4499-9080-658aecd06729"
authors = ["Ahmed Mogahed <a.mogahed@inginne.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "0.10.37"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
